In [230]:
import pandas as pd

In [231]:
from ast import literal_eval

In [232]:
df_movie = pd.read_csv("/home/jinesh/Desktop/movies_metadata.csv")

In [233]:
df_movie.columns

Index([u'adult', u'belongs_to_collection', u'budget', u'genres', u'homepage',
       u'id', u'imdb_id', u'original_language', u'original_title', u'overview',
       u'popularity', u'poster_path', u'production_companies',
       u'production_countries', u'release_date', u'revenue', u'runtime',
       u'spoken_languages', u'status', u'tagline', u'title', u'video',
       u'vote_average', u'vote_count'],
      dtype='object')

In [234]:
#Only keep those features that we require

In [235]:
df_movie=df_movie[['title','genres', 'release_date', 'runtime', 'vote_average', 'vote_count']]

In [236]:
df_movie['release_date'] = df_movie['release_date'].fillna('0-0-0')

In [237]:
def get_release_year(x):
    return int(x.split('-')[0])

In [238]:
df_movie['release_year'] = df_movie['release_date'].apply(get_release_year)

In [239]:
df_movie

,title,genres,release_date,runtime,vote_average,vote_count,release_year
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",1995-10-30,81.0,7.7,5415.0,1995
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",1995-12-15,104.0,6.9,2413.0,1995
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",1995-12-22,101.0,6.5,92.0,1995
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-12-22,127.0,6.1,34.0,1995
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",1995-02-10,106.0,5.7,173.0,1995
5,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",1995-12-15,170.0,7.7,1886.0,1995
6,Sabrina,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",1995-12-15,127.0,6.2,141.0,1995
7,Tom and Huck,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1995-12-22,97.0,5.4,45.0,1995
8,Sudden Death,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1995-12-22,106.0,5.5,174.0,1995
9,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",1995-11-16,130.0,6.6,1194.0,1995
10,The American President,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-11-17,106.0,6.5,199.0,1995
11,Dracula: Dead and Loving It,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",1995-12-22,88.0,5.7,210.0,1995
12,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",1995-12-22,78.0,7.1,423.0,1995
13,Nixon,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",1995-12-22,192.0,7.1,72.0,1995
14,Cutthroat Island,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1995-12-22,119.0,5.7,137.0,1995
15,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1995-11-22,178.0,7.8,1343.0,1995
16,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",1995-12-13,136.0,7.2,364.0,1995
17,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",1995-12-09,98.0,6.5,539.0,1995
18,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",1995-11-10,90.0,6.1,1128.0,1995
19,Money Train,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",1995-11-21,103.0,5.4,224.0,1995
20,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",1995-10-20,105.0,6.4,305.0,1995
21,Copycat,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",1995-10-27,124.0,6.5,199.0,1995
22,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",1995-10-06,132.0,6.0,394.0,1995
23,Powder,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",1995-10-27,111.0,6.3,143.0,1995
24,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",1995-10-27,112.0,7.1,365.0,1995
25,Othello,"[{'id': 18, 'name': 'Drama'}]",1995-12-15,123.0,7.0,33.0,1995
26,Now and Then,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-10-20,100.0,6.6,91.0,1995
27,Persuasion,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",1995-09-27,104.0,7.4,36.0,1995
28,The City of Lost Children,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",1995-05-16,108.0,7.6,308.0,1995
29,Shanghai Triad,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1995-04-30,108.0,6.5,17.0,1995
...,...,...,...,...,...,...,...
45436,The Final Storm,"[{'id': 28, 'name': 'Action'}, {'id': 9648, 'n...",2010-01-01,92.0,3.7,11.0,2010
45437,In a Heartbeat,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",2017-06-01,4.0,8.3,146.0,2017
45438,"Blood, Sweat and Tears","[{'id': 18, 'name': 'Drama'}]",2015-04-02,111.0,6.8,11.0,2015
45439,Jungle Woman,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",1944-06-01,61.0,5.8,2.0,1944
45440,To Be Fat Like Me,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",2007-01-08,89.0,5.0,12.0,2007
45441,Cadet Kelly,"[{'id': 35, 'name': 'Comedy'}]",2002-03-07,101.0,5.2,145.0,2002
45442,The Scheming Gambler's Paradise,[],1905-01-01,3.0,5.0,3.0,1905
45443,The Man with the Rubber Head,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",1901-01-01,3.0,7.6,29.0,1901
45444,The Living Playing Cards,"[{'id': 14, 'name': 'Fantasy'}]",1905-01-01,3.0,6.1,8.0,1905
45445,The Hilarious Posters,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",1906-01-01,3.0,4.5,2.0,1906
45446,The Devilish Tenant,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",1909-01-01,6.0,6.7,12.0,1909
45447,The Untameable Whiskers,[],1904-03-05,3.0,6.0,6.0,1904
45448,The Imperceptable Transmutations,[],1904-01-01,2.0,5.0,2.0,1904
45449,Pooh's Heffalump Halloween Movie,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",2005-09-13,67.0,5.4,7.0,2005
45450,The One-Man Band,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",1900-01-01,1.0,6.5,22.0,1900
45451,The Fat and Lean Wrestling Match,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",1900-01-01,2.0,6.5,6.0,1900
45452,Deep Hearts,"[{'id': 99, 'name': 'Documentary'}]",1981-01-01,58.0,0.0,0.0,1981
45453,Mom,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",2017-07-07,146.0,6.6,14.0,2017
45454,The Morning After,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",2015-01-11,79.0,4.0,2.0,2015
45455,St. Michael Had a Rooster,[],1972-01-01,90.0,6.0,3.0,1972
45456,House of Horrors,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",1946-03-29,65.0,6.3,8.0,1946
45457,Shadow of the Blair Witch,"[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...",2000-10-22,45.0,7.0,2.0,2000
45458,The Burkittsville 7,"[{'id': 27, 'name': 'Horror'}]",2000-10-03,30.0,7.0,1.0,2000
45459,Caged Heat 3000,"[{'id': 878, 'name': 'Science Fiction'}]",1995-01-01,85.0,3.5,1.0,1995
45460,Robin Hood,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",1991-05-13,104.0,5.7,26.0,1991
45461,Subdue,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",0-0-0,90.0,4.0,1.0,0
45462,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",2011-11-17,360.0,9.0,3.0,2011
45463,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",2003-08-01,90.0,3.8,6.0,2003
45464,Satan Triumphant,[],1917-10-21,87.0,0.0,0.0,1917
45465,Queerama,[],2017-06-09,75.0,0.0,0.0,2017

In [240]:
df_movie.drop('release_date',axis=1)

,title,genres,runtime,vote_average,vote_count,release_year
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",81.0,7.7,5415.0,1995
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",104.0,6.9,2413.0,1995
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",101.0,6.5,92.0,1995
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",127.0,6.1,34.0,1995
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",106.0,5.7,173.0,1995
5,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",170.0,7.7,1886.0,1995
6,Sabrina,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",127.0,6.2,141.0,1995
7,Tom and Huck,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",97.0,5.4,45.0,1995
8,Sudden Death,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",106.0,5.5,174.0,1995
9,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",130.0,6.6,1194.0,1995
10,The American President,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",106.0,6.5,199.0,1995
11,Dracula: Dead and Loving It,"[{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...",88.0,5.7,210.0,1995
12,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",78.0,7.1,423.0,1995
13,Nixon,"[{'id': 36, 'name': 'History'}, {'id': 18, 'na...",192.0,7.1,72.0,1995
14,Cutthroat Island,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",119.0,5.7,137.0,1995
15,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",178.0,7.8,1343.0,1995
16,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",136.0,7.2,364.0,1995
17,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",98.0,6.5,539.0,1995
18,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",90.0,6.1,1128.0,1995
19,Money Train,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",103.0,5.4,224.0,1995
20,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",105.0,6.4,305.0,1995
21,Copycat,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",124.0,6.5,199.0,1995
22,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",132.0,6.0,394.0,1995
23,Powder,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",111.0,6.3,143.0,1995
24,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",112.0,7.1,365.0,1995
25,Othello,"[{'id': 18, 'name': 'Drama'}]",123.0,7.0,33.0,1995
26,Now and Then,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",100.0,6.6,91.0,1995
27,Persuasion,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",104.0,7.4,36.0,1995
28,The City of Lost Children,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",108.0,7.6,308.0,1995
29,Shanghai Triad,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",108.0,6.5,17.0,1995
...,...,...,...,...,...,...
45436,The Final Storm,"[{'id': 28, 'name': 'Action'}, {'id': 9648, 'n...",92.0,3.7,11.0,2010
45437,In a Heartbeat,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",4.0,8.3,146.0,2017
45438,"Blood, Sweat and Tears","[{'id': 18, 'name': 'Drama'}]",111.0,6.8,11.0,2015
45439,Jungle Woman,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",61.0,5.8,2.0,1944
45440,To Be Fat Like Me,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",89.0,5.0,12.0,2007
45441,Cadet Kelly,"[{'id': 35, 'name': 'Comedy'}]",101.0,5.2,145.0,2002
45442,The Scheming Gambler's Paradise,[],3.0,5.0,3.0,1905
45443,The Man with the Rubber Head,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",3.0,7.6,29.0,1901
45444,The Living Playing Cards,"[{'id': 14, 'name': 'Fantasy'}]",3.0,6.1,8.0,1905
45445,The Hilarious Posters,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",3.0,4.5,2.0,1906
45446,The Devilish Tenant,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",6.0,6.7,12.0,1909
45447,The Untameable Whiskers,[],3.0,6.0,6.0,1904
45448,The Imperceptable Transmutations,[],2.0,5.0,2.0,1904
45449,Pooh's Heffalump Halloween Movie,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",67.0,5.4,7.0,2005
45450,The One-Man Band,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",1.0,6.5,22.0,1900
45451,The Fat and Lean Wrestling Match,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",2.0,6.5,6.0,1900
45452,Deep Hearts,"[{'id': 99, 'name': 'Documentary'}]",58.0,0.0,0.0,1981
45453,Mom,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",146.0,6.6,14.0,2017
45454,The Morning After,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",79.0,4.0,2.0,2015
45455,St. Michael Had a Rooster,[],90.0,6.0,3.0,1972
45456,House of Horrors,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",65.0,6.3,8.0,1946
45457,Shadow of the Blair Witch,"[{'id': 9648, 'name': 'Mystery'}, {'id': 27, '...",45.0,7.0,2.0,2000
45458,The Burkittsville 7,"[{'id': 27, 'name': 'Horror'}]",30.0,7.0,1.0,2000
45459,Caged Heat 3000,"[{'id': 878, 'name': 'Science Fiction'}]",85.0,3.5,1.0,1995
45460,Robin Hood,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",104.0,5.7,26.0,1991
45461,Subdue,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",90.0,4.0,1.0,0
45462,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",360.0,9.0,3.0,2011
45463,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",90.0,3.8,6.0,2003
45464,Satan Triumphant,[],87.0,0.0,0.0,1917
45465,Queerama,[],75.0,0.0,0.0,2017

In [241]:
df_movie = df_movie.drop('release_date',axis=1)

In [242]:
df_movie.iloc[100]['genres']

"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]"

In [243]:
df_movie['genres'] = df_movie['genres'].fillna('[]')

In [244]:
df_movie['genres'] = df_movie['genres'].apply(literal_eval)

In [245]:
df_movie['genres'] = df_movie['genres'].apply(lambda x: [i['name'] for i in x] if isinstance(x, list) else [])

In [257]:
df_movie['genres'] = df_movie['genres'].apply(lambda x: x[0] if x else [])

df_movie

In [260]:
g = "Drama"

In [261]:
low_year = 1930

In [262]:
high_year = 1950

In [263]:
movies = df_movie.copy()

In [265]:
movies = movies[(movies['release_year'] >= low_year) & (movies['release_year'] <= high_year) & (movies['genres'] == g )]

movies

In [266]:
movies

,title,genres,runtime,vote_average,vote_count,release_year
728,Force of Evil,Drama,78.0,6.6,33.0,1948
731,The Man from Down Under,Drama,103.0,0.0,0.0,1943
867,Liebelei,Drama,88.0,6.3,8.0,1933
870,For Whom the Bell Tolls,Drama,170.0,6.1,41.0,1943
879,Gaslight,Drama,114.0,7.2,73.0,1944
885,Casablanca,Drama,102.0,7.9,1462.0,1942
890,The Little Princess,Drama,93.0,7.0,22.0,1939
893,Gone with the Wind,Drama,238.0,7.7,995.0,1939
895,Sunset Boulevard,Drama,110.0,8.2,533.0,1950
899,All About Eve,Drama,138.0,8.0,367.0,1950
901,Rebecca,Drama,130.0,7.7,346.0,1940
904,Spellbound,Drama,111.0,7.3,166.0,1945
915,Laura,Drama,88.0,7.6,173.0,1944
926,It's a Wonderful Life,Drama,130.0,8.0,1103.0,1946
929,Penny Serenade,Drama,119.0,6.4,23.0,1941
932,Of Human Bondage,Drama,83.0,6.4,26.0,1934
934,Little Lord Fauntleroy,Drama,102.0,6.6,13.0,1936
946,Meet John Doe,Drama,122.0,7.3,52.0,1941
947,Algiers,Drama,96.0,5.8,6.0,1938
949,A Farewell to Arms,Drama,89.0,6.2,29.0,1932
1114,He Walked by Night,Drama,79.0,6.4,17.0,1948
1117,The Children Are Watching Us,Drama,84.0,7.2,11.0,1944
1118,Pastoral Symphony,Drama,110.0,4.7,3.0,1946
1215,M,Drama,117.0,8.0,465.0,1931
1818,All Quiet on the Western Front,Drama,133.0,7.5,166.0,1930
1819,Cimarron,Drama,123.0,5.1,22.0,1931
1820,Grand Hotel,Drama,112.0,6.5,67.0,1932
1821,Cavalcade,Drama,110.0,4.6,17.0,1933
1823,The Great Ziegfeld,Drama,176.0,6.2,19.0,1936
1824,The Life of Emile Zola,Drama,116.0,6.6,19.0,1937
...,...,...,...,...,...,...
41063,Broadway Bad,Drama,61.0,6.0,1.0,1933
41092,Native Land,Drama,89.0,5.7,3.0,1942
41093,No Sad Songs for Me,Drama,88.0,6.0,1.0,1950
41095,The Mayor of 44th Street,Drama,86.0,6.0,1.0,1942
41174,From This Day Forward,Drama,95.0,5.5,4.0,1946
41217,Four Mothers,Drama,86.0,0.0,0.0,1941
41312,The Murderers Are Among Us,Drama,91.0,7.4,5.0,1946
41333,Strange Impersonation,Drama,68.0,5.0,1.0,1946
41421,Finishing School,Drama,73.0,5.1,8.0,1934
41486,They Knew What They Wanted,Drama,96.0,5.5,1.0,1940
41612,Show Girl in Hollywood,Drama,80.0,4.8,3.0,1930
41787,Iron Man,Drama,73.0,0.0,1.0,1931
42246,Juha,Drama,101.0,5.0,1.0,1937
42369,Dishonored Lady,Drama,85.0,4.6,5.0,1947
42594,Nuremberg: Its Lesson for Today,Drama,78.0,0.0,0.0,1948
42652,The Strange Woman,Drama,100.0,6.7,7.0,1946
42653,The Man Who Cheated Himself,Drama,81.0,5.9,8.0,1950
42940,Slaves in Bondage,Drama,70.0,1.0,1.0,1937
43319,Mi adorado Juan,Drama,0.0,0.0,0.0,1950
43657,People of the Mountains,Drama,88.0,9.0,2.0,1942
43658,The Fall of Berlin,Drama,167.0,5.0,1.0,1949
43696,I Accuse My Parents,Drama,68.0,2.9,8.0,1944
43764,Dr. Monica,Drama,53.0,6.0,2.0,1934
43774,Ramona,Drama,84.0,6.0,1.0,1936
44245,The Brute Man,Drama,58.0,4.4,7.0,1946
44532,Anna Karenina,Drama,139.0,5.3,6.0,1948
44563,Tale of the Siberian Land,Drama,114.0,0.0,0.0,1947
44569,Tiger Shark,Drama,77.0,7.8,3.0,1932
44571,Lenin in October,Drama,93.0,5.2,3.0,1937
45439,Jungle Woman,Drama,61.0,5.8,2.0,1944

In [129]:
type(generes)

pandas.core.frame.DataFrame

In [131]:
movies = pd.concat([movies, generes], axis=1, sort=False)

In [136]:
movies = movies.drop('genres',axis=1)

movies

In [138]:
movies

,title,runtime,vote_average,vote_count,release_year,genere_0,genere_1,genere_2,genere_3,genere_4,genere_5,genere_6,genere_7
0,Toy Story,81.0,7.7,5415.0,1995,Animation,Comedy,Family,NaN,NaN,NaN,NaN,NaN
1,Jumanji,104.0,6.9,2413.0,1995,Adventure,Fantasy,Family,NaN,NaN,NaN,NaN,NaN
2,Grumpier Old Men,101.0,6.5,92.0,1995,Romance,Comedy,NaN,NaN,NaN,NaN,NaN,NaN
3,Waiting to Exhale,127.0,6.1,34.0,1995,Comedy,Drama,Romance,NaN,NaN,NaN,NaN,NaN
4,Father of the Bride Part II,106.0,5.7,173.0,1995,Comedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Heat,170.0,7.7,1886.0,1995,Action,Crime,Drama,Thriller,NaN,NaN,NaN,NaN
6,Sabrina,127.0,6.2,141.0,1995,Comedy,Romance,NaN,NaN,NaN,NaN,NaN,NaN
7,Tom and Huck,97.0,5.4,45.0,1995,Action,Adventure,Drama,Family,NaN,NaN,NaN,NaN
8,Sudden Death,106.0,5.5,174.0,1995,Action,Adventure,Thriller,NaN,NaN,NaN,NaN,NaN
9,GoldenEye,130.0,6.6,1194.0,1995,Adventure,Action,Thriller,NaN,NaN,NaN,NaN,NaN
10,The American President,106.0,6.5,199.0,1995,Comedy,Drama,Romance,NaN,NaN,NaN,NaN,NaN
11,Dracula: Dead and Loving It,88.0,5.7,210.0,1995,Comedy,Horror,NaN,NaN,NaN,NaN,NaN,NaN
12,Balto,78.0,7.1,423.0,1995,Family,Animation,Adventure,NaN,NaN,NaN,NaN,NaN
13,Nixon,192.0,7.1,72.0,1995,History,Drama,NaN,NaN,NaN,NaN,NaN,NaN
14,Cutthroat Island,119.0,5.7,137.0,1995,Action,Adventure,NaN,NaN,NaN,NaN,NaN,NaN
15,Casino,178.0,7.8,1343.0,1995,Drama,Crime,NaN,NaN,NaN,NaN,NaN,NaN
16,Sense and Sensibility,136.0,7.2,364.0,1995,Drama,Romance,NaN,NaN,NaN,NaN,NaN,NaN
17,Four Rooms,98.0,6.5,539.0,1995,Crime,Comedy,NaN,NaN,NaN,NaN,NaN,NaN
18,Ace Ventura: When Nature Calls,90.0,6.1,1128.0,1995,Crime,Comedy,Adventure,NaN,NaN,NaN,NaN,NaN
19,Money Train,103.0,5.4,224.0,1995,Action,Comedy,Crime,NaN,NaN,NaN,NaN,NaN
20,Get Shorty,105.0,6.4,305.0,1995,Comedy,Thriller,Crime,NaN,NaN,NaN,NaN,NaN
21,Copycat,124.0,6.5,199.0,1995,Drama,Thriller,NaN,NaN,NaN,NaN,NaN,NaN
22,Assassins,132.0,6.0,394.0,1995,Action,Adventure,Crime,Thriller,NaN,NaN,NaN,NaN
23,Powder,111.0,6.3,143.0,1995,Drama,Fantasy,Science Fiction,Thriller,NaN,NaN,NaN,NaN
24,Leaving Las Vegas,112.0,7.1,365.0,1995,Drama,Romance,NaN,NaN,NaN,NaN,NaN,NaN
25,Othello,123.0,7.0,33.0,1995,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Now and Then,100.0,6.6,91.0,1995,Comedy,Drama,Family,NaN,NaN,NaN,NaN,NaN
27,Persuasion,104.0,7.4,36.0,1995,Drama,Romance,NaN,NaN,NaN,NaN,NaN,NaN
28,The City of Lost Children,108.0,7.6,308.0,1995,Fantasy,Science Fiction,Adventure,NaN,NaN,NaN,NaN,NaN
29,Shanghai Triad,108.0,6.5,17.0,1995,Drama,Crime,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45436,The Final Storm,92.0,3.7,11.0,2010,Action,Mystery,Thriller,Horror,NaN,NaN,NaN,NaN
45437,In a Heartbeat,4.0,8.3,146.0,2017,Family,Animation,Romance,Comedy,NaN,NaN,NaN,NaN
45438,"Blood, Sweat and Tears",111.0,6.8,11.0,2015,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45439,Jungle Woman,61.0,5.8,2.0,1944,Drama,Fantasy,Horror,NaN,NaN,NaN,NaN,NaN
45440,To Be Fat Like Me,89.0,5.0,12.0,2007,Drama,Family,TV Movie,NaN,NaN,NaN,NaN,NaN
45441,Cadet Kelly,101.0,5.2,145.0,2002,Comedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45442,The Scheming Gambler's Paradise,3.0,5.0,3.0,1905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45443,The Man with the Rubber Head,3.0,7.6,29.0,1901,Comedy,Fantasy,Science Fiction,NaN,NaN,NaN,NaN,NaN
45444,The Living Playing Cards,3.0,6.1,8.0,1905,Fantasy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45445,The Hilarious Posters,3.0,4.5,2.0,1906,Fantasy,Comedy,NaN,NaN,NaN,NaN,NaN,NaN
45446,The Devilish Tenant,6.0,6.7,12.0,1909,Fantasy,Comedy,NaN,NaN,NaN,NaN,NaN,NaN
45447,The Untameable Whiskers,3.0,6.0,6.0,1904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45448,The Imperceptable Transmutations,2.0,5.0,2.0,1904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45449,Pooh's Heffalump Halloween Movie,67.0,5.4,7.0,2005,Animation,Family,NaN,NaN,NaN,NaN,NaN,NaN
45450,The One-Man Band,1.0,6.5,22.0,1900,Fantasy,Action,Thriller,NaN,NaN,NaN,NaN,NaN
45451,The Fat and Lean Wrestling Match,2.0,6.5,6.0,1900,Comedy,Fantasy,NaN,NaN,NaN,NaN,NaN,NaN
45452,Deep Hearts,58.0,0.0,0.0,1981,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45453,Mom,146.0,6.6,14.0,2017,Crime,Drama,Thriller,NaN,NaN,NaN,NaN,NaN
45454,The Morning After,79.0,4.0,2.0,2015,Comedy,Drama,NaN,NaN,NaN,NaN,NaN,NaN
45455,St. Michael Had a Rooster,90.0,6.0,3.0,1972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45456,House of Horrors,65.0,6.3,8.0,1946,Horror,Mystery,Thriller,NaN,NaN,NaN,NaN,NaN
45457,Shadow of the Blair Witch,45.0,7.0,2.0,2000,Mystery,Horror,NaN,NaN,NaN,NaN,NaN,NaN
45458,The Burkittsville 7,30.0,7.0,1.0,2000,Horror,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45459,Caged Heat 3000,85.0,3.5,1.0,1995,Science Fiction,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45460,Robin Hood,104.0,5.7,26.0,1991,Drama,Action,Romance,NaN,NaN,NaN,NaN,NaN
45461,Subdue,90.0,4.0,1.0,0,Drama,Family,NaN,NaN,NaN,NaN,NaN,NaN
45462,Century of Birthing,360.0,9.0,3.0,2011,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45463,Betrayal,90.0,3.8,6.0,2003,Action,Drama,Thriller,NaN,NaN,NaN,NaN,NaN
45464,Satan Triumphant,87.0,0.0,0.0,1917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45465,Queerama,75.0,0.0,0.0,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [155]:
def is_genere():
    genere_list = ["genere_{}".format(x) for x in range(0,8)]
    for i in genere_list:
        if x[i] == g:
            return True

In [160]:
n_movies.apply(is_genere)

TypeError: ("'int' object has no attribute '__getitem__'", u'occurred at index title')

['genere_0',
 'genere_1',
 'genere_2',
 'genere_3',
 'genere_4',
 'genere_5',
 'genere_6',
 'genere_7']

genere_0
genere_1
genere_2
genere_3
genere_4
genere_5
genere_6
genere_7

In [154]:
n_movies['genere_0']

0              Animation
1              Adventure
2                Romance
3                 Comedy
4                 Comedy
5                 Action
6                 Comedy
7                 Action
8                 Action
9              Adventure
10                Comedy
11                Comedy
12                Family
13               History
14                Action
15                 Drama
16                 Drama
17                 Crime
18                 Crime
19                Action
20                Comedy
21                 Drama
22                Action
23                 Drama
24                 Drama
25                 Drama
26                Comedy
27                 Drama
28               Fantasy
29                 Drama
              ...
45436             Action
45437             Family
45438              Drama
45439              Drama
45440              Drama
45441             Comedy
45442                NaN
45443             Comedy
45444            Fantasy
45445            Fantasy
45446            Fantasy
45447                NaN
45448                NaN
45449          Animation
45450            Fantasy
45451             Comedy
45452        Documentary
45453              Crime
45454             Comedy
45455                NaN
45456             Horror
45457            Mystery
45458             Horror
45459    Science Fiction
45460              Drama
45461              Drama
45462              Drama
45463             Action
45464                NaN
45465                NaN
Name: genere_0, Length: 45466, dtype: object

In [150]:
n_movies.apply(is_genere)

TypeError: ("'int' object has no attribute '__getitem__'", u'occurred at index title')

In [90]:
movies = movies[(movies['release_year'] >= low_year) & (movies['release_year'] <= high_year)]

In [104]:
movies

,title,genres,runtime,vote_average,vote_count,release_year
587,Snow White and the Seven Dwarfs,"[Fantasy, Animation, Family]",83.0,6.9,1973.0,1937
589,Pinocchio,"[Animation, Family]",88.0,6.9,1412.0,1940
728,Force of Evil,"[Drama, Action, Crime]",78.0,6.6,33.0,1948
731,The Man from Down Under,"[Drama, War]",103.0,0.0,0.0,1943
737,Kim,"[Family, Adventure]",113.0,7.0,5.0,1950
833,Crows and Sparrows,[],113.0,5.0,1.0,1949
867,Liebelei,"[Drama, Romance]",88.0,6.3,8.0,1933
870,For Whom the Bell Tolls,"[Drama, History, Romance, Thriller]",170.0,6.1,41.0,1943
871,The Philadelphia Story,"[Comedy, Romance]",112.0,7.7,196.0,1940
878,It Happened One Night,"[Comedy, Romance]",105.0,7.7,283.0,1934
879,Gaslight,"[Drama, Mystery, Thriller, Crime]",114.0,7.2,73.0,1944
880,The Gay Divorcee,"[Comedy, Music, Romance]",107.0,7.2,17.0,1934
885,Casablanca,"[Drama, Romance]",102.0,7.9,1462.0,1942
886,The Maltese Falcon,"[Mystery, Crime, Thriller]",100.0,7.8,435.0,1941
890,The Little Princess,"[Drama, Comedy, Family]",93.0,7.0,22.0,1939
891,Meet Me in St. Louis,"[Comedy, Music, Romance]",113.0,6.8,66.0,1944
892,The Wizard of Oz,"[Adventure, Family, Fantasy]",102.0,7.4,1689.0,1939
893,Gone with the Wind,"[Drama, Romance, War]",238.0,7.7,995.0,1939
895,Sunset Boulevard,[Drama],110.0,8.2,533.0,1950
896,Citizen Kane,"[Mystery, Drama]",119.0,8.0,1244.0,1941
898,Golden Earrings,"[Adventure, Romance]",95.0,4.8,3.0,1947
899,All About Eve,[Drama],138.0,8.0,367.0,1950
900,The Women,"[Comedy, Drama]",133.0,6.4,26.0,1939
901,Rebecca,"[Drama, Mystery]",130.0,7.7,346.0,1940
902,Foreign Correspondent,"[Mystery, Thriller, War]",120.0,7.0,86.0,1940
903,Notorious,"[Thriller, Drama, Romance]",102.0,7.8,345.0,1946
904,Spellbound,"[Drama, Mystery, Thriller]",111.0,7.3,166.0,1945
907,Father of the Bride,"[Comedy, Drama, Family, Romance]",92.0,6.6,43.0,1950
909,Ninotchka,"[Comedy, Romance]",110.0,7.3,77.0,1939
913,The Adventures of Robin Hood,"[Action, Adventure, Romance]",102.0,7.6,170.0,1938
...,...,...,...,...,...,...
44563,Tale of the Siberian Land,"[Drama, Romance]",114.0,0.0,0.0,1947
44569,Tiger Shark,"[Drama, Romance]",77.0,7.8,3.0,1932
44571,Lenin in October,"[Drama, History]",93.0,5.2,3.0,1937
44592,Медведь,[Comedy],NaN,0.0,0.0,1938
44594,Sinbad il marinaio,[Adventure],116.0,5.4,6.0,1947
44635,The Great Piggy Bank Robbery,"[Animation, Comedy, Family]",8.0,6.9,11.0,1946
44637,Bunker Hill Bunny,[],7.0,7.6,5.0,1950
44651,Moving Day,[Animation],9.0,5.6,7.0,1936
44653,Donald's Nephews,[Animation],8.0,5.5,11.0,1938
44686,Fast and Furry-Ous,[Animation],7.0,7.0,15.0,1949
44688,Hurdy-Gurdy Hare,[],7.0,6.5,2.0,1950
44690,Bugs Bunny and the Three Bears,[],7.0,7.0,6.0,1944
44705,Wolf! Wolf!,[Animation],6.0,5.5,2.0,1944
44706,Stupidstitious Cat,[],0.0,7.0,1.0,1947
44707,McDougal's Rest Farm,[],0.0,0.0,0.0,1947
44912,Three Songs About Lenin,[Documentary],59.0,6.4,5.0,1934
44942,The Wrong Road,"[Crime, Drama]",62.0,5.0,1.0,1937
44944,San Giovanni decollato,[Comedy],0.0,5.7,3.0,1940
44945,I due orfanelli,[Comedy],0.0,3.5,4.0,1947
44952,Death Mills (Die Todesmühlen),"[War, Documentary]",22.0,8.0,1.0,1945
44955,Murder with Pictures,"[Crime, Mystery]",69.0,5.0,1.0,1936
44959,Totò Sceicco,[Comedy],NaN,6.5,8.0,1950
44988,La nao Capitana,"[Adventure, History]",NaN,0.0,0.0,1947
44999,Wild Rose,[Romance],70.0,0.0,0.0,1932
45001,Popeye the Sailor Meets Sindbad the Sailor,"[Comedy, Animation]",16.0,6.4,10.0,1936
45030,The Story of Menstruation,[Animation],10.0,6.0,8.0,1946
45089,Swineherd and Shepherd,"[Romance, Comedy]",87.0,3.0,1.0,1941
45237,Julia Misbehaves,"[Comedy, Romance]",99.0,6.8,3.0,1948
45439,Jungle Woman,"[Drama, Fantasy, Horror]",61.0,5.8,2.0,1944
45456,House of Horrors,"[Horror, Mystery, Thriller]",65.0,6.3,8.0,1946