In [26]:
import pandas as pd

In [27]:
# Formula for calculating number
"""
weighted rating
WR = (v/v+m)xR + (m/v+m)xC
where
v = # of votes 
m = is the minimum number of votes required for the movie to be in the chart (the prerequisite)
R = mean rating of movie
C is mean rating of all movies.
"""

'\nweighted rating\nWR = (v/v+m)xR + (m/v+m)xC\nwhere\nv = # of votes \nm = is the minimum number of votes required for the movie to be in the chart (the prerequisite)\nR = mean rating of movie\nC is mean rating of all movies.\n'

In [28]:
#Load movies into csv data frame
df_movie = pd.read_csv("/home/jinesh/Desktop/movies_metadata.csv")

In [29]:
m = df_movie['vote_count'].quantile(0.80)

In [30]:
# now filter movies who has runtime between 45 mins to 300 mins to qualify movies.

new_df_movies = df_movie[(df_movie['runtime'] >= 45) & (df_movie['runtime'] <= 300)]

In [31]:
new_df_movies = new_df_movies[new_df_movies['vote_count'] > m]
#print(new_df_movies.shape)


# Calculate C
C = new_df_movies['vote_average'].mean()

In [32]:
C

6.3527918781725887

In [33]:
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    # Compute the weighted score
    return (v/(v+m) * R) + (m/(m+v) * C)

In [34]:
# Compute the score using the weighted_rating function defined above
new_df_movies['score'] = new_df_movies.apply(weighted_rating, axis=1)

In [37]:
new_df_movies.sort_values(by=['score'], ascending=False)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,score
10309,False,NaN,13200000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,19404,tt0112870,hi,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",...,1.000000e+08,190.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Come... Fall In Love,Dilwale Dulhania Le Jayenge,False,9.1,661.0,8.906807
314,False,NaN,25000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,278,tt0111161,en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,...,2.834147e+07,142.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,False,8.5,8358.0,8.487231
834,False,"{'id': 230, 'name': 'The Godfather Collection'...",6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.thegodfather.com/,238,tt0068646,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",...,2.450664e+08,175.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,An offer you can't refuse.,The Godfather,False,8.5,6024.0,8.482325
40251,False,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 16, ...",https://www.funimationfilms.com/movie/yourname/,372058,tt5311514,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,...,3.552983e+08,106.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Your Name.,False,8.5,1030.0,8.400592
12481,False,"{'id': 263, 'name': 'The Dark Knight Collectio...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,155,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,...,1.004558e+09,152.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Why So Serious?,The Dark Knight,False,8.3,12269.0,8.292097
2843,False,NaN,63000000,"[{'id': 18, 'name': 'Drama'}]",http://www.foxmovies.com/movies/fight-club,550,tt0137523,en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,...,1.008538e+08,139.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Mischief. Mayhem. Soap.,Fight Club,False,8.3,9678.0,8.289992
292,False,NaN,8000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,680,tt0110912,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",...,2.139288e+08,154.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Just because you are a character doesn't mean ...,Pulp Fiction,False,8.3,8670.0,8.288835
522,False,NaN,22000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",http://www.schindlerslist.com/,424,tt0108052,en,Schindler's List,The true story of how businessman Oskar Schind...,...,3.213656e+08,195.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,"Whoever saves one life, saves the world entire.",Schindler's List,False,8.3,4436.0,8.278297
23673,False,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,244786,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",...,1.309200e+07,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,False,8.3,4376.0,8.278003
5481,False,NaN,15000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",http://movies.disney.com/spirited-away,129,tt0245429,ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,...,2.749251e+08,125.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,False,8.3,3968.0,8.275769
2211,False,NaN,20000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,637,tt0118799,it,La vita è bella,A touching story of an Italian book seller of ...,...,2.294000e+08,116.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"An unforgettable fable that proves love, famil...",Life Is Beautiful,False,8.3,3643.0,8.273636
1178,False,"{'id': 230, 'name': 'The Godfather Collection'...",13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,240,tt0071562,en,The Godfather: Part II,In the continuing saga of the Corleone crime f...,...,4.754284e+07,200.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"I don't feel I have to wipe everybody out, Tom...",The Godfather: Part II,False,8.3,3418.0,8.271926
1152,False,NaN,3000000,"[{'id': 18, 'name': 'Drama'}]",NaN,510,tt0073486,en,One Flew Over the Cuckoo's Nest,While serving time for insanity at a state men...,...,1.089813e+08,133.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"If he's crazy, what does that make you?",One Flew Over the Cuckoo's Nest,False,8.3,3001.0,8.268089
1176,False,"{'id': 119674, 'name': 'Psycho Collection', 'p...",806948,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",NaN,539,tt0054215,en,Psycho,When larcenous real estate clerk Marion Crane ...,...,3.200000e+07,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The master of suspense moves his cameras into ...,Psycho,False,8.3,2405.0,8.260342
1184,False,NaN,30000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,311,tt0087843,en,Once Upon a Time in America,A former Prohibition-era Jewish gangster retur...,...,0.000000e+00,229.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"Crime, passion and lust for power - Sergio Leo...",Once Upon a Time in America,False,8.3,1104.0,8.215632
351,False,NaN,55000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,13,tt0109830,en,Forrest Gump,A man with a low IQ has accomplished great thi...,...,6.779454e+08,142.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The world will never be the same, once you've ...",Forrest Gump,False,8.2,8147.0,8.188732
1154,False,"{'id': 10, 'name': 'Star Wars Collection', 'po...",18000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,1891,tt0080684,en,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",...,5.384000e+08,124.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Adventure Continues...,The Empire Strikes Back,False,8.2,5998.0,8.184729
18465,False,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,77338,tt1675434,fr,Intouchables,A true story of two men who should never have ...,...,4.264809e+08,112.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes you have to reach into someone else'...,The Intouchables,False,8.2,5410.0,8.183084
289,False,NaN,16000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,101,tt0110413,fr,Léon,"Leon, the top hit man in New York, has earned ...",...,4.528497e+07,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"If you want a job done well, hire a professional.",Leon: The Professional,False,8.2,4293.0,8.178734
3030,False,NaN,60000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",http://thegreenmile.warnerbros.com/,497,tt0120689,en,The Green Mile,A supernatural tale set on death row in a Sout...,...,2.846000e+08,189.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,Miracles do happen.,The Green Mile,False,8.2,4166.0,8.178093
1170,False,NaN,25000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.warnerbros.com/goodfellas,769,tt0099685,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",...,4.683639e+07,145.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}, {'is...",Released,Three Decades of Life in the Mafia.,GoodFellas,False,8.2,3211.0,8.171677
2216,False,NaN,20000000,"[{'id': 18, 'name': 'Drama'}]",http://www.historyx.com/,73,tt0120586,en,American History X,Derek Vineyard is paroled after serving 3 year...,...,2.387513e+07,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some Legacies Must End.,American History X,False,8.2,3120.0,8.170864
1161,False,NaN,350000,"[{'id': 18, 'name': 'Drama'}]",NaN,389,tt0050083,en,12 Angry Men,The defense and the prosecution have rested an...,...,1.000000e+06,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Life is in their hands. Death is on their minds.,12 Angry Men,False,8.2,2130.0,8.157633
9698,False,NaN,24000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 16, 'na...",NaN,4935,tt0347149,ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",...,2.347105e+08,119.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The two lived there,Howl's Moving Castle,False,8.2,2049.0,8.155998
2884,False,NaN,26500000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,128,tt0119698,ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",...,1.593753e+08,134.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,False,8.2,2041.0,8.155830
5878,False,NaN,3300000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://cidadededeus.globo.com/,598,tt0317248,pt,Cidade de Deus,Cidade de Deus is a shantytown that started du...,...,3.064177e+07,130.0,"[{'iso_639_1': 'pt', 'name': 'Português'}]",Released,"If you run you're dead... if you stay, you're ...",City of God,False,8.2,1852.0,8.151440
877,False,NaN,1000000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,567,tt0047396,en,Rear Window,"Professional photographer L.B. ""Jeff"" Jeffries...",...,3.676431e+07,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It only takes one witness to spoil the perfect...,Rear Window,False,8.2,1531.0,8.141581
5553,False,NaN,3700000,"[{'id': 16, 'name': 'Animation'}, {'id': 18, '...",NaN,12477,tt0095327,ja,火垂るの墓,"In the latter part of World War II, a boy and ...",...,0.000000e+00,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,"At 4 and 14, they tried to live on",Grave of the Fireflies,False,8.2,974.0,8.109804
1910,False,NaN,2000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,346,tt0047478,ja,七人の侍,A samurai answers a village's request for prot...,...,2.718410e+05,207.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,False,8.2,892.0,8.101953
1132,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,11216,tt0095765,it,Nuovo Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",...,1.199040e+07,124.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,"A celebration of youth, friendship, and the ev...",Cinema Paradiso,False,8.2,834.0,8.095520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,False,"{'id': 261203, 'name': 'Street Fighter', 'post...",35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,11667,tt0111301,en,Street Fighter,Col. Guile and various other martial arts hero...,...,9.942352e+07,102.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The fight to save the world is on!,Street Fighter,False,4.1,330.0,4.396420
13662,False,"{'id': 178106, 'name': 'Darko Collection', 'po...",4000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",http://www.sdarko.com/,17532,tt1231277,en,S. Darko,"S. Darko follows Samantha Darko, the younger s...",...,4.100000e+06,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,S. Darko,False,3.6,124.0,4.391032
9444,False,"{'id': 10522, 'name': 'Starship Troopers Colle...",7000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 27, '...",NaN,10304,tt0367093,en,Starship Troopers 2: Hero of the Federation,In the sequel to Paul Verhoeven's loved/revile...,...,0.000000e+00,88.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They're Coming Back to Wipe Us Out!,Starship Troopers 2: Hero of the Federation,False,3.8,176.0,4.364777
4963,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",NaN,11535,tt0246894,en,Rollerball,From the director of Die Hard comes this high-...,...,0.000000e+00,98.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,Go Ballistic,Rollerball,False,3.4,106.0,4.346408
29939,False,"{'id': 96671, 'name': 'The Human Centipede Col...",0,"[{'id': 27, 'name': 'Horror'}]",NaN,94365,tt1883367,en,The Human Centipede 3 (Final Sequence),Taking inspiration from The Human Centipede fi...,...,0.000000e+00,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,100% politically incorrect,The Human Centipede 3 (Final Sequence),False,3.7,159.0,4.334639
1486,False,"{'id': 43064, 'name': 'Speed Collection', 'pos...",160000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,1639,tt0120179,en,Speed 2: Cruise Control,Sandra Bullock and Jason Patric star as a youn...,...,1.645081e+08,121.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"As the stakes get higher, the ride gets even f...",Speed 2: Cruise Control,False,4.1,439.0,4.330347
10464,False,NaN,18000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.sonypictures.com/homevideo/thefog/i...,791,tt0432291,en,The Fog,"Trapped within an eerie mist, the residents of...",...,4.620143e+07,100.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Their PAST Has Come Back To HAUNT THEM,The Fog,False,3.8,191.0,4.329625
16616,False,"{'id': 9888, 'name': 'Home Alone Collection', ...",0,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",NaN,12536,tt0329200,en,Home Alone 4,Kevin McCallister's parents have split up. Now...,...,0.000000e+00,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Home Alone 4,False,3.9,239.0,4.324358
7939,False,NaN,100000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,314,tt0327554,en,Catwoman,Liquidated after discovering a corporate consp...,...,8.210238e+07,104.0,"[{'iso_639_1': 'es', 'name': 'Español'}, {'iso...",Released,CATch her in IMAX,Catwoman,False,4.2,833.0,4.321902
11229,False,NaN,40000000,"[{'id': 9648, 'name': 'Mystery'}, {'id': 53, '...",NaN,9708,tt0450345,en,The Wicker Man,A sheriff investigating the disappearance of a...,...,3.875507e+07,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some sacrifices must be made,The Wicker Man,False,4.0,355.0,4.290468
1491,False,"{'id': 120794, 'name': 'Batman Collection', 'p...",125000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,415,tt0118688,en,Batman & Robin,Along with crime-fighting partner Robin and ne...,...,2.382071e+08,125.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Strength. Courage. Honor. And loyalty.,Batman & Robin,False,4.2,1447.0,4.271904
1603,False,"{'id': 9818, 'name': 'Mortal Kombat Collection...",30000000,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",NaN,9823,tt0119707,en,Mortal Kombat: Annihilation,A group of heroic warriors has only six days t...,...,5.137686e+07,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The world was created in six days, so too shal...",Mortal Kombat: Annihilation,False,3.8,225.0,4.264144
5422,False,NaN,40000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",NaN,9544,tt0295254,en,FearDotCom,"With four corpses on his hands, New York City ...",...,1.890202e+07,101.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The last site you'll ever see.,FearDotCom,False,3.2,106.0,4.210510
28207,False,NaN,4000000,"[{'id': 53, 'name': 'Thriller'}]",http://www.theboynextdoorfilm.com/,241251,tt3181822,en,The Boy Next Door,A recently cheated on married woman falls for ...,...,5.242586e+07,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Moment She Couldn't Resist. An Obsession He ...,The Boy Next Door,False,4.1,1034.0,4.203911
18101,False,NaN,79000000,"[{'id': 35, 'name': 'Comedy'}]",http://www.jackandjill-movie.com/,71880,tt0810913,en,Jack and Jill,"Jack Sadelstein, a successful advertising exec...",...,1.496738e+08,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His twin sister is coming for the holidays... ...,Jack and Jill,False,4.0,619.0,4.175844
12358,False,NaN,30000000,"[{'id': 35, 'name': 'Comedy'}]",http://www.meetthespartans.com/,7278,tt1073498,en,Meet the Spartans,From the creators of Scary Movie and Date Movi...,...,8.464683e+07,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The Bigger the Hit, The Harder They Fall",Meet the Spartans,False,3.8,370.0,4.103904
10809,False,NaN,20000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,10073,tt0466342,en,Date Movie,Spoof of romantic comedies which focuses on a ...,...,4.854843e+07,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,An Unprotected Comedy,Date Movie,False,3.6,225.0,4.100508
8607,False,NaN,19000,"[{'id': 27, 'name': 'Horror'}]",NaN,22293,tt0060666,en,Manos: The Hands of Fate,A family gets lost on the road and stumbles up...,...,0.000000e+00,74.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It's Shocking! It's Beyond Your Imagination!,Manos: The Hands of Fate,False,2.0,56.0,4.053204
21238,False,"{'id': 286023, 'name': 'Sharknado Collection',...",1000000,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 27,...",http://www.theasylum.cc/product.php?id=230,205321,tt2724064,en,Sharknado,"A freak hurricane hits Los Angeles, causing ma...",...,0.000000e+00,86.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Enough said!,Sharknado,False,3.8,484.0,4.039025
3998,False,"{'id': 2366, 'name': 'The Jaws Collection', 'p...",23000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 53, '...",NaN,580,tt0093300,en,Jaws: The Revenge,"After another deadly shark attack, Ellen Brody...",...,5.188101e+07,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"This time, it’s personal.",Jaws: The Revenge,False,3.5,227.0,4.014944
39554,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",http://www.backinthedaythemovie.com/,368596,tt3349772,en,Back in the Day,A young boxer is taken under the wing of a mob...,...,0.000000e+00,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"When things that don't seem to matter anymore,...",Back in the Day,False,2.8,97.0,4.008433
24413,False,NaN,16000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.leftbehindmovie.com/,218043,tt2467046,en,Left Behind,A small group of survivors are left behind aft...,...,1.968292e+07,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The End Begins,Left Behind,False,3.7,396.0,3.997398
9710,False,"{'id': 43072, 'name': 'The Mask Collection', '...",84000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",NaN,10214,tt0362165,en,Son of the Mask,"Tim Avery, an aspiring cartoonist, finds himse...",...,0.000000e+00,94.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Who's next?,Son of the Mask,False,3.6,346.0,3.947575
6723,False,"{'id': 117927, 'name': 'House of the Dead Coll...",7000000,"[{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...",http://www.house-of-the-dead.com/,11059,tt0317676,en,House of the Dead,"Set on an island off the coast, a techno rave ...",...,1.381818e+07,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,You won't last the night.,House of the Dead,False,2.8,106.0,3.938715
17708,False,"{'id': 225961, 'name': 'Birdemic Collection', ...",0,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",http://www.birdemic.com/,40016,tt1316037,en,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,...,0.000000e+00,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Why did the eagles and vultures attack?,Birdemic: Shock and Terror,False,2.1,69.0,3.886887
9651,False,"{'id': 149704, 'name': 'Alone in the Dark Coll...",20000000,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",NaN,12142,tt0369226,en,Alone in the Dark,Edward Carnby is a private investigator specia...,...,1.044281e+07,96.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Can mankind defeat the army of darkness unleas...,Alone in the Dark,False,3.1,174.0,3.826070
12911,False,NaN,25000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",http://www.disastermovie.net/,13805,tt1213644,en,Disaster Movie,"In DISASTER MOVIE, the filmmaking team behind ...",...,1.410928e+07,87.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Your favorite movies are going to be destroyed.,Disaster Movie,False,3.1,250.0,3.642132